import type { CmcdKeySpec } from './CmcdKeySpec.ts'

const EVENTS = ['bc', 'ps', 'pr', 'e', 't', 'c', 'b', 'm', 'um', 'pe', 'pc', 'rr', 'as', 'ae', 'abs', 'abe', 'sk', 'ce', 'h']
const MEDIA = ['a', 'v', 'av', 'tt', 'c', 'o']

/** One row per reserved key of CTA-5004-B Table 1, plus the version 1 `nrr` key. */
export const CMCD_KEY_SPECS: Readonly<Record<string, CmcdKeySpec>> = {
	ab: { type: 'ot-list', modes: 'both', round: 1, supersededBy: 'br', v1: 'absent' },
	bg: { type: 'boolean', modes: 'both', requiredOn: 'b', omitDefault: false, v1: 'absent' },
	bl: { type: 'ot-list', modes: 'both', round: 100, v1: 'scalar' },
	br: { type: 'ot-list', modes: 'both', round: 1, requiredOn: 'bc', v1: 'scalar' },
	bs: { type: 'boolean', modes: 'both', omitDefault: false },
	bsa: { type: 'ot-list', modes: 'both', round: 1, v1: 'absent' },
	bsd: { type: 'ot-list', modes: 'both', round: 1, v1: 'absent' },
	bsda: { type: 'ot-list', modes: 'both', round: 1, v1: 'absent' },
	cen: { type: 'string', modes: 'event', onlyOn: 'ce', requiredOn: 'ce', max: 64 },
	cid: { type: 'string', modes: 'both', requiredOn: 'c', max: 128 },
	cmsdd: { type: 'string', modes: 'event', onlyOn: 'rr' },
	cmsds: { type: 'string', modes: 'event', onlyOn: 'rr' },
	cs: { type: 'string', modes: 'both', v1: 'absent' },
	d: { type: 'integer', modes: 'both', round: 1, ot: MEDIA },
	dfa: { type: 'integer', modes: 'both', round: 1, v1: 'absent' },
	dl: { type: 'integer', modes: 'both', round: 100 },
	e: { type: 'token', modes: 'event', requiredOn: 'always', tokens: EVENTS },
	ec: { type: 'string-list', modes: 'both', requiredOn: 'e', v1: 'absent' },
	h: { type: 'string', modes: 'event', requiredOn: 'h', max: 128 },
	lab: { type: 'ot-list', modes: 'both', round: 1, supersededBy: 'lb', v1: 'absent' },
	lb: { type: 'ot-list', modes: 'both', round: 1, v1: 'absent' },
	ltc: { type: 'integer', modes: 'both', round: 1, v1: 'absent' },
	msd: { type: 'integer', modes: 'both', round: 1, v1: 'absent' },
	mtp: { type: 'ot-list', modes: 'both', round: 100, v1: 'scalar' },
	nor: { type: 'nor', modes: 'both', v1: 'string' },
	nr: { type: 'boolean', modes: 'both', omitDefault: false, v1: 'absent' },
	nrr: { type: 'string', modes: 'both' },
	ot: { type: 'token', modes: 'both', tokens: ['m', 'a', 'v', 'av', 'i', 'c', 'tt', 'k', 'o'] },
	pb: { type: 'ot-list', modes: 'both', round: 1, v1: 'absent' },
	pr: { type: 'decimal', modes: 'both', requiredOn: 'pr', omitDefault: 1 },
	pt: { type: 'integer', modes: 'both', round: 1, v1: 'absent' },
	rc: { type: 'integer', modes: 'event', round: 1, onlyOn: 'rr' },
	rtp: { type: 'integer', modes: 'both', round: 100 },
	sf: { type: 'token', modes: 'both', tokens: ['d', 'h', 'e', 's', 'o'] },
	sid: { type: 'string', modes: 'both', max: 64 },
	smrt: { type: 'string', modes: 'event', onlyOn: 'rr' },
	sn: { type: 'integer', modes: 'both', round: 1, v1: 'absent' },
	st: { type: 'token', modes: 'both', tokens: ['v', 'l', 'll'] },
	sta: { type: 'token', modes: 'both', requiredOn: 'ps', tokens: ['s', 'p', 'k', 'r', 'a', 'w', 'e', 'f', 'q', 'd'], v1: 'absent' },
	su: { type: 'boolean', modes: 'both', omitDefault: false },
	tab: { type: 'ot-list', modes: 'both', round: 1, supersededBy: 'tb', v1: 'absent' },
	tb: { type: 'ot-list', modes: 'both', round: 1, v1: 'scalar' },
	tbl: { type: 'ot-list', modes: 'both', round: 100, v1: 'absent' },
	tpb: { type: 'ot-list', modes: 'both', round: 1, ot: ['a', 'v', 'av', 'c'], v1: 'absent' },
	ts: { type: 'integer', modes: 'event', round: 1, requiredOn: 'always' },
	ttfb: { type: 'integer', modes: 'event', round: 1, onlyOn: 'rr' },
	ttfbb: { type: 'integer', modes: 'event', round: 1, onlyOn: 'rr' },
	ttlb: { type: 'integer', modes: 'event', round: 1, onlyOn: 'rr' },
	url: { type: 'string', modes: 'event', onlyOn: 'rr', requiredOn: 'rr' },
	v: { type: 'integer', modes: 'both', round: 1, requiredOn: 'always', omitDefault: 1, v1: 'absent' },
}
